{
 "title": "Sui Validator Dashboard",
 "description": "Sui Validator Node dashboard. Uses Grafana agent with node exporter plugin/integration enabled. ",
 "tags": [
  "sui",
  "fullnode"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "query": "sui" },
   {
    "name": "chain",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"},chain)"
    }
   },
   {
    "name": "validator",
    "query": {
     "query": "label_values(node_uname_info,validator)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Sui Metrics Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Validator Score",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "consensus_handler_scores{authority=\"$validator\"}",
     "legendFormat": "{{authority}}"
    },
    { "expr": "avg(consensus_handler_scores)", "legendFormat": "network_average_score" }
   ]
  },
  {
   "title": "Instance Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{chain=\"$chain\", instance!=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sui Client Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance, version) (uptime)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sui Node Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Validator Live",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consensus_handler_scores{authority=\"$validator\"} > bool 150",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Input Objects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_input_objects_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Txns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_transaction_certificates", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sync Speed TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(total_transaction_certificates[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txns Effects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_transaction_effects", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Highest Checkpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "highest_known_checkpoint", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sync'd Checkpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "highest_synced_checkpoint", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current_epoch", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time Until Next epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(19000 - last_executed_checkpoint % 19000) / rate(last_executed_checkpoint[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoch Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "epoch_total_duration", "legendFormat": "__auto" }
   ]
  },
  { "title": "Validator Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_executed_checkpoint", "legendFormat": "Last Executed Checkpoint" },
    { "expr": "highest_synced_checkpoint", "legendFormat": "Highest Synced Checkpoint" },
    { "expr": "highest_verified_checkpoint", "legendFormat": "Highest Verified Checkpoint" },
    { "expr": "last_certified_checkpoint", "legendFormat": "Last Certified Checkpoint" },
    { "expr": "highest_known_checkpoint", "legendFormat": "Highest Known Checkpoint" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current_round", "legendFormat": "Current Round" },
    {
     "expr": "highest_processed_round{source=\"own\"}",
     "legendFormat": "Highest Processed Round"
    },
    {
     "expr": "transactions_included_in_checkpoint",
     "legendFormat": "Txns in Checkpoint"
    },
    { "expr": "total_transaction_orders", "legendFormat": "Total Txns Orders" },
    {
     "expr": "total_handle_certificate_attempts",
     "legendFormat": "Total Handle Certificate Attempts"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "primary_network_peers", "legendFormat": "Primary Network Peers" },
    { "expr": "worker_network_peers", "legendFormat": "Worker Network Peers" },
    { "expr": "sui_network_peers", "legendFormat": "Sui Network Peers" },
    { "expr": "skipped_consensus_txns", "legendFormat": "Skipped Consensus Txns" },
    { "expr": "total_signature_errors", "legendFormat": "Total Signature Errors" }
   ]
  },
  {
   "title": "Checkpointing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Checkpoints",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "targets": [
      { "expr": "highest_known_checkpoint", "legendFormat": "{{__name__}}" },
      { "expr": "highest_verified_checkpoint", "legendFormat": "{{__name__}}" },
      { "expr": "last_executed_checkpoint", "legendFormat": "{{__name__}}" }
     ]
    },
    {
     "title": "Highest Synced Checkpoint ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "targets": [
      { "expr": "highest_synced_checkpoint", "legendFormat": "{{__name__}}" }
     ]
    },
    {
     "title": "Checkpoint Execution Backlog",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "(last_executed_checkpoint - highest_known_checkpoint)",
       "legendFormat": "checkpoint execution backlog"
      }
     ]
    },
    {
     "title": "Checkpoint Synchronization Backlog",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "(highest_synced_checkpoint- highest_known_checkpoint)",
       "legendFormat": "checkpoint execution backlog"
      }
     ]
    },
    {
     "title": "Last Executed Checkpoint (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "(rate(last_executed_checkpoint[2m]))",
       "legendFormat": "checkpoint execution backlog"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Certificates Created (rate)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "(rate(certificates_created[2m]))",
       "legendFormat": "checkpoint execution backlog"
      }
     ]
    },
    {
     "title": "Current Rounds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      { "expr": "current_round", "legendFormat": "{{__name__}}" },
      { "expr": "highest_processed_round", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Last Committed Round",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      { "expr": "last_committed_round", "legendFormat": "{{__name__}}" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Finalized TPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      { "expr": "(rate(num_shared_obj_tx[2m]))", "legendFormat": "{{host}} shared_object" },
      {
       "expr": " (rate(total_transaction_certificates[2m])) - (rate(num_shared_obj_tx[2m]))",
       "legendFormat": "{{host}} owned_object"
      }
     ]
    },
    {
     "title": "Certificate Processing Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "(rate(validator_service_handle_certificate_non_consensus_latency_sum[5m])) / (rate(validator_service_handle_certificate_non_consensus_latency_count[2m]))",
       "legendFormat": "{{host}} owned_object"
      },
      {
       "expr": "(rate(validator_service_handle_certificate_consensus_latency_sum[5m])) / (rate(validator_service_handle_certificate_consensus_latency_count[2m]))",
       "legendFormat": "{{host}} shared_object"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sui Network Peers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      { "expr": "(sui_network_peers)", "legendFormat": "{{__name__}}" }
     ]
    },
    {
     "title": "Primary Network Peers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      { "expr": "primary_network_peers", "legendFormat": "{{__name__}}" }
     ]
    },
    {
     "title": "Worker Network Peers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "targets": [
      { "expr": "worker_network_peers", "legendFormat": "{{__name__}}" }
     ]
    }
   ]
  },
  {
   "title": "Additional Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inbound Requests Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "rate(sui_inbound_request_latency_sum[1m])",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Inbound Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
     "targets": [
      { "expr": "sui_inbound_requests", "legendFormat": "{{route}}" }
     ]
    },
    {
     "title": "Sync Lag",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "clamp_min(highest_synced_checkpoint - highest_known_checkpoint, 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outbound Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
     "targets": [
      { "expr": "sui_outbound_requests", "legendFormat": "{{route}}" }
     ]
    },
    {
     "title": "Outbound Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
     "targets": [
      {
       "expr": "rate(sui_outbound_request_latency_sum[1m])",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Outbound Req. Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
     "targets": [
      { "expr": "sui_outbound_request_errors", "legendFormat": "{{route}}" }
     ]
    },
    {
     "title": "Sequencing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
     "targets": [
      { "expr": "sequencing_certificate_success", "legendFormat": "{{__name__}}" },
      {
       "expr": "sequencing_certificate_failures",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "sequencing_certificate_inflight",
       "legendFormat": "{{__name__}}"
      },
      { "expr": "sequencing_certificate_attempt", "legendFormat": "{{__name__}}" }
     ]
    },
    {
     "title": "Enqueued Certs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
     "targets": [
      {
       "expr": "transaction_manager_num_enqueued_certificates",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Voting Right",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
     "targets": [
      { "expr": "current_voting_right", "legendFormat": "{{__name__}}" }
     ]
    },
    {
     "title": "User Key Comparison",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 65 },
     "targets": [
      { "expr": "user_key_comparison_count", "legendFormat": "{{cf_name}}" }
     ]
    },
    {
     "title": "Tallying Scores by validator",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 65 },
     "targets": [
      {
       "expr": "consensus_handler_scores{authority=\"$validator\"}",
       "legendFormat": "{{validator}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy",
     "type": "gauge",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})"
      }
     ]
    },
    {
     "title": "Sys Load (5m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (5 min average)",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load5{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "Sys Load (15m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (15 min average)",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load15{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "Root FS Used",
     "type": "gauge",
     "description": "Used Root FS",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
      }
     ]
    },
    {
     "title": "SWAP Used",
     "type": "gauge",
     "description": "Used Swap",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} )) * 100"
      }
     ]
    },
    {
     "title": "System Uptime",
     "type": "stat",
     "description": "System uptime",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Disk Space Used",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "RootFS Total",
     "type": "stat",
     "description": "Total RootFS",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "description": "Total RAM",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
      }
     ]
    }
   ]
  }
 ]
}